"""inital migration

Revision ID: 33f649e8f493
Revises: 
Create Date: 2023-06-11 18:49:04.666560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f649e8f493'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description_1', sa.String(length=3000), nullable=True),
    sa.Column('description_2', sa.String(length=3000), nullable=True),
    sa.Column('description_3', sa.String(length=3000), nullable=True),
    sa.Column('water_min', sa.Float(), nullable=True),
    sa.Column('water_max', sa.Float(), nullable=True),
    sa.Column('light_min', sa.Float(), nullable=True),
    sa.Column('light_max', sa.Float(), nullable=True),
    sa.Column('harvest_begin', sa.DateTime(), nullable=True),
    sa.Column('harvest_end', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('edited_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_name'), ['name'], unique=False)

    op.create_table('sensor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_type_type'), ['type'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('smart_leaf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('box_idx', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_leaf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_leaf_mac_address'), ['mac_address'], unique=True)

    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smart_leaf_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('measured_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_type.id'], ),
    sa.ForeignKeyConstraint(['smart_leaf_id'], ['smart_leaf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    with op.batch_alter_table('smart_leaf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_leaf_mac_address'))

    op.drop_table('smart_leaf')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('sensor_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_type_type'))

    op.drop_table('sensor_type')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_name'))

    op.drop_table('plant')
    # ### end Alembic commands ###
