"""temperature min and max for plant model

Revision ID: 95dd447758e1
Revises: 33f649e8f493
Create Date: 2023-06-27 14:55:34.714405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dd447758e1'
down_revision = '33f649e8f493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperature_max', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('temperature_max')
        batch_op.drop_column('temperature_min')

    # ### end Alembic commands ###
